//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vozila
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vozila()
        {
            this.Servis = new HashSet<Servi>();
        }
    
        public int IDVozilo { get; set; }
        public string Tip { get; set; }
        public string Marka { get; set; }
        public Nullable<int> StanjeKilometra { get; set; }
        public Nullable<int> GodinaProizvodnje { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servi> Servis { get; set; }
    }
}
